stages:
- stage: Development
  jobs:
  - job: Build
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
        # Comment out until we can figure out how to not report coverage twice
        # node_12_x:
        #   node_version: 12.x
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - script: npm i -g npm
      displayName: Update npm
    - script: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      displayName: Update yarn
    - script: npm i -g lerna
      displayName: Install lerna
    - script: lerna bootstrap
      displayName: Bootstrap dependencies
    - script: yarn pixeloven:compile
      displayName: Compile PixelOven packages
    - script: yarn pixeloven:lint
      displayName: Lint PixelOven packages
    - script: yarn pixeloven:test
      displayName: Test PixelOven packages
    - script: yarn pixeloven:build:production
      displayName: Build PixelOven apps
    # Run against examples now -- eventually this should be setup as a true integration step
    - script: yarn examples:compile
      displayName: Compile example packages
    - script: yarn examples:lint
      displayName: Lint example packages
    - script: yarn examples:test
      displayName: Test example packages
    - script: yarn examples:build:production
      displayName: Build example apps
    - script: yarn codecov -t $(CODECOV_TOKEN)
      displayName: Report code coverage